const moodFaces: Record<string, string> = {
  neutral: '(・_・)',
  happy: '(＾▽＾)',
  sad: '(T_T)',
  angry: '(ಠ_ಠ)',
  surprised: '(°o°)',
  content: '(￣︶￣)',
  cheerful: '(＾ｖ＾)',
  chipper: '(≧◡≦)',
  confused: '(・_・?)',
  curious: '(・o・)',
  disappointed: '(；_；)',
  disgusted: '(>_<)',
  excited: '＼(^o^)／',
  focused: '(•_•)',
  frustrated: '(>_<)',
  grateful: '(˘⌣˘)',
  gleeful: 'ヽ(＾Д＾)ﾉ',
  giddy: '(*^_^*)',
  gloomy: '(；一_一)',
  grumpy: '(－_－＃)',
  imperious: '(`‾ʖ̫ ‾)',
  indifferent: '(－_－)',
  impressed: '(°ロ°)',
  inspired: '(ง°ل͜°)ง',
  melancholy: '(；⌣̀_⌣́)',
  lonely: '(；_；)',
  nervous: '(・_・;）',
  playful: '(＾ω＾)',
  proud: '(￣^￣)',
  relaxed: '(￣︶￣)',
  sardonic: '(¬_¬)',
  sassy: '(*≧▽≦)',
  satisfied: '(￣︶￣)',
  scared: '(>_<)',
  'self-righteous': '(｀へ´*)ノ',
  serious: '(－_－)',
  servile: 'm(_ _)m',
  stressed: '(>_<)',
  tired: 'Zzz...\n(－_－)',
  unimpressed: '(－_－)',
};

export function getMoodFace(mood: string): string {
  return moodFaces[mood] || moodFaces.neutral;
}
